# Generated by Django 4.1.6 on 2023-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Musique', 'Musique'), ('Sport', 'Sport'), ('Cinema', 'Cinema')], max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('nbe_participant', models.IntegerField(default=0)),
                ('evt_date', models.DateTimeField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
