# Generated by Django 4.1.6 on 2023-02-03 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_please check out the even date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='please check out the even date',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2023, 2, 3, 16, 44, 7, 427363))), name='please check out the even date'),
        ),
    ]
